
"""
389. Find the Difference
https://leetcode.com/problems/find-the-difference/
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
Input: s = "abcd", t = "abcde" Output: "e"
Input: s = "", t = "y" Output: "y"
Input: s = "a", t = "aa" Output: "a"
Input: s = "ae", t = "aea" Output: "a"
"""
    def findTheDifference(self, s: str, t: str) -> str:
        s, t = sorted(s), sorted(t)

        for i in range(len(t)):
            if i >=  len(s) or s[i] != t[i]:
                return t[i]
        return ''
